[project]
name = "pjt-ditto-agent-hs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=8.31.0",
    "langchain>=0.3.14",
    "langchain-google-vertexai>=2.0.7",
    "langgraph>=0.2.61",
]
